name: robotics
channels:
- defaults
dependencies:
- bleach=2.1.3=py35_0
- ca-certificates=2017.08.26=h1d4fec5_0
- certifi=2018.1.18=py35_0
- cycler=0.10.0=py35hc4d5149_0
- dbus=1.12.2=hc3f9b76_1
- decorator=4.2.1=py35_0
- entrypoints=0.2.3=py35h48174a2_2
- expat=2.2.5=he0dffb1_0
- fontconfig=2.12.4=h88586e7_1
- freetype=2.8=hab7d2ae_1
- glib=2.53.6=h5d9569c_2
- gmp=6.1.2=h6c8ec71_1
- gst-plugins-base=1.12.4=h33fb286_0
- gstreamer=1.12.4=hb53b477_0
- html5lib=1.0.1=py35h2f9c1c0_0
- icu=58.2=h9c2bf20_1
- intel-openmp=2018.0.0=hc7b2577_8
- ipykernel=4.8.2=py35_0
- ipython=6.2.1=py35hd850d2a_1
- ipython_genutils=0.2.0=py35hc9e07d0_0
- ipywidgets=7.1.2=py35_0
- jedi=0.11.1=py35_0
- jinja2=2.10=py35h480ab6d_0
- jpeg=9b=h024ee3a_2
- jsonschema=2.6.0=py35h4395190_0
- jupyter=1.0.0=py35_4
- jupyter_client=5.2.2=py35_0
- jupyter_console=5.2.0=py35h4044a63_1
- jupyter_core=4.4.0=py35ha89e94b_0
- kiwisolver=1.0.1=py35hcb1117a_0
- libedit=3.1=heed3624_0
- libffi=3.2.1=hd88cf55_4
- libgcc-ng=7.2.0=h7cc24e2_2
- libgfortran-ng=7.2.0=h9f7466a_2
- libpng=1.6.34=hb9fc6fc_0
- libsodium=1.0.15=hf101ebd_0
- libstdcxx-ng=7.2.0=h7a57d05_2
- libxcb=1.12=hcd93eb1_4
- libxml2=2.9.7=h26e45fe_0
- markupsafe=1.0=py35h4f4fcf6_1
- matplotlib=2.2.0=py35hbc4b006_0
- mistune=0.8.3=py35_0
- mkl=2018.0.1=h19d6760_4
- nbconvert=5.3.1=py35hc5194e3_0
- nbformat=4.4.0=py35h12e6e07_0
- ncurses=6.0=h9df7e31_2
- notebook=5.4.0=py35_0
- numpy=1.14.1=py35ha266831_2
- openssl=1.0.2n=hb7f436b_0
- pandoc=1.19.2.1=hea2e7c5_1
- pandocfilters=1.4.2=py35h1565a15_1
- parso=0.1.1=py35h1b200a3_0
- pcre=8.41=hc27e229_1
- pexpect=4.4.0=py35_0
- pickleshare=0.7.4=py35hd57304d_0
- pip=9.0.1=py35_5
- prompt_toolkit=1.0.15=py35hc09de7a_0
- ptyprocess=0.5.2=py35h38ce0a3_0
- pygments=2.2.0=py35h0f41973_0
- pyparsing=2.2.0=py35h041ed72_1
- pyqt=5.6.0=py35h0e41ada_5
- python=3.5.4=hc3d631a_27
- python-dateutil=2.6.1=py35h90d5b31_1
- pytz=2018.3=py35_0
- pyzmq=17.0.0=py35h14c3975_0
- qt=5.6.2=hd25b39d_14
- qtconsole=4.3.1=py35h4626a06_0
- readline=7.0=ha6073c6_4
- send2trash=1.5.0=py35_0
- setuptools=38.5.1=py35_0
- simplegeneric=0.8.1=py35_2
- sip=4.18.1=py35h9eaea60_2
- six=1.11.0=py35h423b573_1
- sqlite=3.22.0=h1bed415_0
- terminado=0.8.1=py35_1
- testpath=0.3.1=py35had42eaf_0
- tk=8.6.7=hc745277_3
- tornado=5.0=py35_0
- tqdm=4.19.5=py35_0
- traitlets=4.3.2=py35ha522a97_0
- wcwidth=0.1.7=py35hcd08066_0
- webencodings=0.5.1=py35hb6cf162_1
- wheel=0.30.0=py35hd3883cf_1
- widgetsnbextension=3.1.4=py35_0
- xz=5.2.3=h55aa19d_2
- zeromq=4.2.3=h439df22_3
- zlib=1.2.11=ha838bed_2
- pip:
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.2
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - prompt-toolkit==1.0.15
prefix: /home/lale/anaconda3/envs/robotics
